// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    typetype: function(text, callback, keypress) {
      var charDelay, deferreds, interval, t;
      charDelay = 100;
      interval = function(index) {
        var lastchar, nextchar;
        lastchar = text[index - 1];
        nextchar = text[index];
        return Math.random() * charDelay * (function() {
          switch (lastchar) {
            case nextchar:
              return 1.6;
            case '.':
            case '!':
              return 16;
            case ',':
            case ';':
              return 8;
            case ' ':
              return 3;
            case lastchar === '\n' && nextchar !== '\n':
              return 10;
            default:
              return 2;
          }
        })();
      };
      deferreds = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          t = this[_i];
          _results.push((function(t) {
            return $.Deferred(function(deferred) {
              var updateChar;
              updateChar = function(limit) {
                $(t).html(text.substr(0, limit));
                if (keypress != null) {
                  keypress.call(t, limit);
                }
                if (limit < text.length) {
                  return setTimeout(function() {
                    return updateChar(limit + 1);
                  }, interval(limit));
                } else {
                  return deferred.resolve();
                }
              };
              return updateChar(1);
            }).done(function() {
              return callback != null ? callback.call(t) : void 0;
            });
          })(t));
        }
        return _results;
      }).call(this);
      return $.when.apply($, deferreds);
    }
  });

}).call(this);
