// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    typetype: function(text) {
      return this.each(function(i, item) {
        return $(this).html(text);
      });
    }
  });

}).call(this);
