// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    typetype: function(text) {
      var textarea;
      textarea = this.first();
      return $.Deferred(function(deferred) {
        var updateText;
        updateText = function(textarea, text, limit, deferred) {
          textarea.text(text.substr(0, limit));
          if (limit < text.length) {
            return setTimeout(function() {
              return updateText(textarea, text, limit + 1, deferred);
            }, 100);
          } else {
            return deferred.resolve();
          }
        };
        return updateText(textarea, text, 1, deferred);
      });
    }
  });

}).call(this);
