// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    typetype: function(text) {
      var textarea;
      textarea = this.first();
      return $.Deferred((function(_this) {
        return function(deferred) {
          return setTimeout(function() {
            textarea.html(text);
            return deferred.resolve();
          }, 1000);
        };
      })(this));
    }
  });

}).call(this);
